### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/osml-cdk-constructs#33]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by drduhe** [comment]
fixed

**Comment by vprince1** [comment]
I still see references to older versions. Can you kindly fix them?

![image](https://github.com/aws-solutions-library-samples/osml-cdk-constructs/assets/11996632/b1c9a949-1538-40de-998a-eec957fc4ded)

**Comment by drduhe** [comment]
https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/42
